// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2Q8io4YT2aFb8somxWhYXQ
// Component: 6wPn25ZNUt3CI
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import CopyableLink from "../../CopyableLink"; // plasmic-import: YLm9tZK9aFCAD/component
import { useScreenVariants as useScreenVariantsinFmIpItQIc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: INFm_ipItQ-IC/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_argazki_a_artment_landing.module.css"; // plasmic-import: 2Q8io4YT2aFb8somxWhYXQ/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 6wPn25ZNUt3CI/css

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsinFmIpItQIc()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"Apartment at Roses by Argazki.Art"}</title>
        <meta
          key="og:title"
          property="og:title"
          content={"Apartment at Roses by Argazki.Art"}
        />

        <meta
          key="description"
          property="og:description"
          name="description"
          content={
            "Family apartment in the town of Santa Margarida (Roses), with awesome views of the valley and the mountainous part of Alt Empordà, where you can enjoy splendid sunsets every afternoon."
          }
        />

        <meta
          key="og:image"
          property="og:image"
          content={
            "https://site-assets.plasmic.app/d3edfa7124379fb0ff7268af5020df61.jpg"
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__wg1Hp)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___70Vyw)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__t3CUt)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___8TrMq)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lcgvQ
                    )}
                  >
                    {"Bienvenidos"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jatEa
                    )}
                  >
                    {"Welcome"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__viwbp
                    )}
                  >
                    {"Bienvenue"}
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__ltVFf)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iOe8S
                  )}
                >
                  {
                    "Para reservas o mas informacion:\nFor reservations and more information:\nPour réservations et plus d'informations :"
                  }
                </div>

                <p.PlasmicLink
                  data-plasmic-name={"link"}
                  data-plasmic-override={overrides.link}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  platform={"nextjs"}
                >
                  {"Airbnb"}
                </p.PlasmicLink>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1Qbyt
                  )}
                >
                  {"o"}
                </div>

                <CopyableLink
                  data-plasmic-name={"copyableLink"}
                  data-plasmic-override={overrides.copyableLink}
                  className={classNames("__wab_instance", sty.copyableLink)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___36Oo
                    )}
                  >
                    {"hello@argazki.art"}
                  </div>
                </CopyableLink>
              </div>
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox__alq96)} />
          </div>

          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox___1Zoh)}>
              <p.PlasmicImg
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/argazki_a_artment_landing/images/apartmentThumbnailsjpg.jpeg",
                  fullWidth: 3000,
                  fullHeight: 4000,
                  aspectRatio: undefined
                }}
              />
            </div>
          ) : null}

          <div className={classNames(projectcss.all, sty.freeBox__lMtnL)}>
            <div className={classNames(projectcss.all, sty.freeBox__z8Ju)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9R64K
                )}
              >
                {"ES:"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cQwqQ
                )}
              >
                {
                  "Apartamento familiar en la localidad de Santa Margarida (Roses), con magníficas vistas al valle y la parte montañosa de Alt Empordà, donde podrá disfrutar de espléndidas puestas de sol todas las tardes. Ideal para una estancia corta o larga; alojamiento totalmente equipado y situado en una residencia segura con parking privado y portero.\n\nA 1 km de la playa y en una calle tranquila, el apartamento cuenta con un gran espacio exterior: dos piscinas, una para adultos y otra para niños; zona de barbacoa, pista de tenis, volley y zona verde vallada ideal para relajarse o jugar con niños.\nEn el interior del piso: salón con cama de matrimonio y armario, sofá-cama, tv y wifi, cocina y baño totalmente equipados, terraza con mesita y zona chillout.\n\nEl edificio está situado en una zona turística pero apartado del centro. Ideal si lo que se busca es comodidad y tranquilidad. Perfecto para los amantes del turismo con bicicleta, ya que hay parking específico para bicicletas disponible en el edificio y los caminos de alrededor invitan a dar un paseo.\n\nSe encuentra muy cerca de varios supermercados (LIDL, Carrefour y Mercadona) y muchos de ellos abren hasta los domingos. También está a 6 minutos en bici del Karting Roses y Aquabrava y 8 minutos en bici de las principales playas de la zona.\n\nHabrá que informar que en Catalunya, por la legislación vigente hay una tasa turística de 1€ por día y por persona mayor de 14 años que no está incluida en el precio y se recogerá en el momento de la llegada.\n"
                }
              </div>
            </div>
          </div>

          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__o08Pk)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__al8T
                )}
              >
                {"EN:"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3C4Jq
                )}
              >
                {
                  "Family apartment in the town of Santa Margarida (Roses), with awesome views of the valley and the mountainous part of Alt Empordà, where you can enjoy splendid sunsets every afternoon. Ideal for a short or long stay. Fully equipped accommodation located in a secure residence with private parking and doorman.\n\nIs located at 1 km from the beach and in a quiet street, the apartment has a large outdoor space: two swimming pools, one for adults and one for children; barbecue area, tennis and volleyball field, and fenced green area ideal for relaxing or playing with children.\nInside the apartment: living room with double bed and wardrobe, sofa bed, TV and Wi-Fi, fully equipped kitchen and bathroom, terrace with table and chillout area.\n\nThe building is located in a tourist area but away from the center. Ideal if what you are looking for is comfort and tranquility. Perfect for lovers of bicycle tourism, as there is specific parking for bicycles available in the building and the surrounding paths invite you to take a walk.\n\nIt is very close to several supermarkets (LIDL, Carrefour and Mercadona) and many of them are open until Sundays. It is also 6 minutes by bike from Karting Roses and Aquabrava and 8 minutes by bike from the main beaches in the area.\n\nIt should be noted that in Catalonia, due to current legislation, there is a tourist tax of €1 per day and per person over 14 years of age, which is not included in the price and will be collected at the time of arrival.\n"
                }
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "link", "copyableLink", "img"],
  link: ["link"],
  copyableLink: ["copyableLink"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    copyableLink: makeNodeComponent("copyableLink"),
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
